# Generated by Django 5.2.6 on 2025-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('event_date', models.DateTimeField(verbose_name='Дата проведения')),
                ('location', models.CharField(blank=True, max_length=128, null=True, verbose_name='Место проведения')),
                ('rsvp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка RSVP')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Исходная ссылка')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'events',
            },
        ),
    ]
