# Generated by Django 5.2.6 on 2025-09-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="api_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="API ID"
            ),
        ),
    ]
