# Generated by Django 5.2.6 on 2025-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('prize', models.CharField(blank=True, max_length=128, null=True, verbose_name='Приз')),
                ('deadline', models.DateTimeField(verbose_name='Срок подачи заявок')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Исходная ссылка')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'db_table': 'competitions',
                'ordering': ['deadline'],
            },
        ),
    ]
